sudo: required

language: node_js

services:
- mysql

before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS mysql_kiss_orm_test"

after_success:
- bash <(curl -s https://codecov.io/bash)
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
