sudo: required

language: node_js

services:
- mysql

before_install:
- sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS mysql_kiss_orm_test"

after_success:
- bash <(curl -s https://codecov.io/bash)
